import Head from 'next/head'
import Header from '../components/Header'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Airbnb 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1>Hello Airbnb</h1> */}

      {/* header */}

       <Header></Header>
      
      
      
      
      
      {/* banner */}
     
    </div>
  )
}
