import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home({ exploreData,cardData }) {
  exploreData;
  return (
    <div className="">
      <Head>
        <title>Airbnb 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}

      <Header />

      {/* banner */}
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearbuy</h2>

         <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {/* pull some data from server -API endpoints */}
          {exploreData?.map(({ img, distance, location }) => (
            <SmallCard
              img={img}
              distance={distance}
              location={location}
              key={img}
            />
          ))}
         </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
         <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3 ">
         {cardData?.map(({img,title}) =>(
            <MediumCard key={img} img={img} title={title}/>
          ))}

         </div>
        </section>
      </main>
    </div>
  );
}

//?to get the api request
export async function getStaticProps() {
  const exploreData = await fetch("https://links.papareact.com/pyp").then(
    (res) => res.json()
  );
  const cardData = await fetch("https://links.papareact.com/zp1").then((res) => res.json());
  return {
    props: {
      exploreData,
      cardData
    },
  };
}
